# Generated by Django 3.0.3 on 2020-11-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_date', models.DateField()),
                ('hebrew_date', models.CharField(max_length=20)),
                ('hebrew_year', models.CharField(max_length=10)),
                ('sof_zman_1', models.TimeField(blank=True, null=True)),
                ('sof_zman_2', models.TimeField(blank=True, null=True)),
                ('sof_zman_tefila', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MazelTov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mazel_tov', models.TextField(max_length=400)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazel', to='luach.MyDate')),
            ],
        ),
        migrations.CreateModel(
            name='DayImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day', to='luach.MyDate')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='luach.Images')),
            ],
        ),
    ]
